version: "3"
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.prod
      args:
        API_USER: ${DB_USER_API}
        API_PASS: ${DB_PASS_API}
    image: jamieoliveredwards/catalogue-db
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    image: jamieoliveredwards/catalogue-api
    restart: always
    working_dir: /usr/api
    command: node index.js
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - PORT=${API_PORT}
      - DB_URI=mongodb://${DB_USER_API}:${DB_PASS_API}@db:27017/catalogue
    links:
      - db
      - client_app
    networks:
      - backend
  client_app:
    build:
      context: ./clientApp
      dockerfile: Dockerfile.prod
      args:
        API_BASE: http://192.168.0.12:${API_PORT}
    image: jamieoliveredwards/catalogue-app
    restart: always
    ports:
      - "4201:80"

volumes:
  mongodb_data:

networks:
  backend:
