version: "3"
services:
  api:
    build: ./api
    restart: always
    working_dir: /usr/api
    command: sh -c 'npm install && concurrently "tsc -w" "nodemon dist"'
    volumes:
      - ./api:/usr/api:delegated
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    links:
      - client_app
  client_app:
    build: ./clientApp
    restart: always
    working_dir: /usr/clientApp
    command: npm start
    volumes:
      - ./clientApp:/usr/clientApp:delegated
    ports:
      - "4200:4200"
