version: "3"
services:
  db:
    image: mongo:4.4.0
    restart: always
    volumes:
      - ./db/mongodata:/data/db
      - ./db/startup/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27018:27017"
  api:
    build: ./api
    restart: always
    working_dir: /usr/api
    command: sh -c 'npm install && concurrently "tsc -w" "nodemon dist"'
    volumes:
      - ./api:/usr/api:delegated
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    links:
      - db
      - client_app
  client_app:
    build: ./clientApp
    restart: always
    working_dir: /usr/clientApp
    command: npm start
    volumes:
      - ./clientApp:/usr/clientApp:delegated
    ports:
      - "4200:4200"
